from .Checks import is_any
from .Checks import is_ip
from .Checks import is_packet_length
from .Checks import is_discard_class
from .Checks import is_atm
from .Checks import is_security_group
from .Checks import is_protocol
from .Checks import is_vlan
from .Checks import is_mpls